### ISSUE TITLE
[Bug] Custom Resource Definitions are always seen as not equal

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#109]
When reconciling, the following log message always appears when the reconciliation of a specific component occurs:

```
updating resource; kind: [CustomResourceDefinition], name: [my-custom-resource], namespace: []
```

This is because when comparing the existing CRD resource in the cluster versus a newly submitted resource, the 2 items are seen as not equal (see https://github.com/vmware-tanzu-labs/operator-builder/blob/main/pkg/plugins/workload/v1/scaffolds/templates/int/resources/resources.go#L319).

This does not affect the overall functionality, but it will be an annoying and confusing message potentially to end users.

**Comment by lander2k2** [comment]
Skip update log message for CRD, i.e. if the object is a CRD, skip with no log message.  Or change log level.
