### ISSUE TITLE
Docker build fails due to omitted copy of internal directory

### ISSUE THREAD

**Issue by lander2k2** [vmware-tanzu-labs/operator-builder#137]
Dockerfile currently includes the following:

```
# Copy the go source
COPY main.go main.go
COPY apis/ apis/
COPY controllers/ controllers/

```

It should have `COPY internal/ internal/` included before the build

**Comment by scottd018** [comment]
This was closed via https://github.com/vmware-tanzu-labs/operator-builder/pull/136
