### ISSUE TITLE
docs(video): Building a Working Kubernetes Operator in 5 Minutes

### ISSUE THREAD

**Issue by scottd018** [vmware-tanzu-labs/operator-builder#149]
This is a video that would be helpful to see what it takes to build a running kubernetes operator within 5 minutes.

**Comment by lander2k2** [comment]
Note: highlight the distinct roles:
- operator developer
- operator user

**Comment by scottd018** [comment]
This can be closed out as video was posted to https://www.youtube.com/watch?v=gdB2pInO-kg
