### ISSUE TITLE
Remove limitation of 1 standalone workload per cluster

### ISSUE THREAD

**Issue by lander2k2** [vmware-tanzu-labs/operator-builder#208]
Currently if we create two different instances of a standalone workload in a single cluster, we get the following error:

```
2021-11-11T14:44:52.861-0500    INFO    controllers.apps.WebStore       expected only 1 resource of kind: [WebStore]; found 2
```

I think the standalone workloads accidentally inherited this limitation from the workload collections

**Comment by scottd018** [comment]
@lander2k2 this should be fixed here https://github.com/vmware-tanzu-labs/operator-builder/pull/196/files#diff-176de775fe3401ccf2798bd12ee8084a6223b8619252532eb76188da50c1e871L110 which has already been merged in.

Can you rebase and give it a try for me again to double-check that we are fixed?

**Comment by lander2k2** [comment]
@scottd018 Indeed we are good.  I must've been using the 0.4.0 release when I ran into this.
