### ISSUE TITLE
Nice to have: `defaultNamespace` specifically related to when using `clusterScoped: false`

### ISSUE THREAD

**Issue by ahuffman** [vmware-tanzu-labs/operator-builder#45]
The generated config/samples come with no metadata.namespace.  It would be nice to supply a default one when using CRDs that are able to be namespaced.  That way they don't just get created in the default k8s namespace.

**Comment by scottd018** [comment]
Confirmed, this can be attained by setting the `metadata.namespace` field on a namespace-scoped resource.

@lander2k2 reading this message a little close, it looks like the comment `The generated config/samples come with no metadata.namespace` might actually be able to be addressed.  I think we may want to consider adding a **commented** `metadata.namespace` field to the generated sample to remind consumers of their resources that they have the ability to do this.  I think this may help avoid confusion.
